/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paradinhas.siscoimp.view;

/**
 *
 * @author gab
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPaneCtrl = new javax.swing.JDesktopPane();
        appointmentBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        doctorsBtn = new javax.swing.JButton();
        doctorsBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISCOIMP");
        setBackground(new java.awt.Color(10, 10, 10));

        desktopPaneCtrl.setBackground(new java.awt.Color(0, 0, 0));

        appointmentBtn.setBackground(new java.awt.Color(204, 255, 204));
        appointmentBtn.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        appointmentBtn.setForeground(new java.awt.Color(0, 0, 0));
        appointmentBtn.setText("Agendamentos");
        appointmentBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        appointmentBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentBtnActionPerformed(evt);
            }
        });

        profileBtn.setBackground(new java.awt.Color(204, 255, 204));
        profileBtn.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(0, 0, 0));
        profileBtn.setText("Perfil");
        profileBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        profileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        doctorsBtn.setBackground(new java.awt.Color(204, 255, 204));
        doctorsBtn.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        doctorsBtn.setForeground(new java.awt.Color(0, 0, 0));
        doctorsBtn.setText("Médicos");
        doctorsBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        doctorsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        doctorsBtn1.setBackground(new java.awt.Color(204, 255, 204));
        doctorsBtn1.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        doctorsBtn1.setForeground(new java.awt.Color(0, 0, 0));
        doctorsBtn1.setText("Familiares");
        doctorsBtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        doctorsBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        desktopPaneCtrl.setLayer(appointmentBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPaneCtrl.setLayer(profileBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPaneCtrl.setLayer(doctorsBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPaneCtrl.setLayer(doctorsBtn1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneCtrlLayout = new javax.swing.GroupLayout(desktopPaneCtrl);
        desktopPaneCtrl.setLayout(desktopPaneCtrlLayout);
        desktopPaneCtrlLayout.setHorizontalGroup(
            desktopPaneCtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneCtrlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointmentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorsBtn1)
                .addContainerGap(843, Short.MAX_VALUE))
        );
        desktopPaneCtrlLayout.setVerticalGroup(
            desktopPaneCtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneCtrlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopPaneCtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileBtn)
                    .addComponent(appointmentBtn)
                    .addComponent(doctorsBtn)
                    .addComponent(doctorsBtn1))
                .addContainerGap(681, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneCtrl)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneCtrl)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        //desktopPaneCtrl.removeAll();
        Profile profile = new Profile();
        desktopPaneCtrl.add(profile).setVisible(true);
    }//GEN-LAST:event_profileBtnActionPerformed

    private void appointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentBtnActionPerformed

        AppointmentsList apptList = new AppointmentsList();
        desktopPaneCtrl.add(apptList).setVisible(true);
    }//GEN-LAST:event_appointmentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentBtn;
    private javax.swing.JDesktopPane desktopPaneCtrl;
    private javax.swing.JButton doctorsBtn;
    private javax.swing.JButton doctorsBtn1;
    private javax.swing.JButton profileBtn;
    // End of variables declaration//GEN-END:variables
}
