/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paradinhas.siscoimp.view.emergencyInfo;

import paradinhas.siscoimp.models.EmergencyInfo;
import paradinhas.siscoimp.view.MainFrame;
import paradinhas.siscoimp.view.templates.ElementTemplate;

/**
 *
 * @author gab
 */
public class EmergencyInfoElement extends ElementTemplate {

    int index;
    EmergencyInfo emg;

    /**
     * Creates new form AppointmentTemplateD
     */
    public EmergencyInfoElement(EmergencyInfo emg, int i) {
        initComponents();
        this.emg = emg;
        this.index = i;
        titleField.setText(emg.getTitle());

        switch (emg.getUrg()) {
            case EMERGENCY:
                urgencyField.setText("Emergência");
                urgencyField.setBackground(new java.awt.Color(255, 102, 102));
                break;
            case VERY_URGENT:
                urgencyField.setText("Muito Urgente");
                urgencyField.setBackground(new java.awt.Color(255, 153, 51));
                break;
            case URGENT:
                urgencyField.setText("Urgente");
                urgencyField.setBackground(new java.awt.Color(255, 255, 51));
                break;
            case LESS_URGENT:
                urgencyField.setText("Pouco Urgente");
                urgencyField.setBackground(new java.awt.Color(102, 255, 102));
                break;
            case NON_URGENT:
                urgencyField.setText("Não Urgente");
                urgencyField.setBackground(new java.awt.Color(51, 153, 255));
                break;
            default:
                urgencyField.setText("Não Urgente");
                urgencyField.setBackground(new java.awt.Color(51, 153, 255));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleField = new javax.swing.JLabel();
        urgencyField = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        titleField.setFont(new java.awt.Font("FreeSans", 1, 36)); // NOI18N
        titleField.setText("titulo");

        urgencyField.setBackground(new java.awt.Color(51, 153, 255));
        urgencyField.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        urgencyField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        urgencyField.setText("Não Urgente");
        urgencyField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        urgencyField.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleField, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(urgencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(titleField))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(urgencyField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        MainFrame.getInstance().showEmgInfoCad(emg, index);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titleField;
    private javax.swing.JLabel urgencyField;
    // End of variables declaration//GEN-END:variables
}
