/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paradinhas.siscoimp.view.appointment;

import java.text.SimpleDateFormat;
import paradinhas.siscoimp.models.Appointment;
import paradinhas.siscoimp.view.MainFrame;
import paradinhas.siscoimp.view.templates.ElementTemplate;

/**
 *
 * @author gab
 */
public class AppointmentElement extends ElementTemplate {


    
    /**
     * Creates new form AppointmentTemplateD
     */
    
    Appointment appt;
    int index;
    
    public AppointmentElement(Appointment appt, int i) {
        initComponents();
        this.appt = appt;
        this.index = i;
        
        dataField.setText(new SimpleDateFormat("dd/MM/yyyy").format(appt.getDate()));
        titleField.setText(appt.getTitle());
        
        switch (appt.getType()) {
            case EXAM:
                typeField.setText("Exame");
                break;
            case CONSULT:
                typeField.setText("Consulta");
                break;
            default:
                typeField.setText("Nenhum");
                break;
        }
        
        switch (appt.getStatus()){
            case CONCLUDED:
                statusField.setText("Concluído");
                statusField.setBackground(new java.awt.Color(102, 255, 102));
                break;
            case IN_PROGRESS:
                statusField.setText("Em andamento");
                statusField.setBackground(new java.awt.Color(255, 153, 51));
                break;
            case EXPIRED:
                statusField.setText("Expirado");
                statusField.setBackground(new java.awt.Color(255, 102, 102));
                break;
            default:
                statusField.setText("Expirado");
                statusField.setBackground(new java.awt.Color(255, 102, 102));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleField = new javax.swing.JLabel();
        dataField = new javax.swing.JLabel();
        typeField = new javax.swing.JLabel();
        statusField = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        titleField.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        titleField.setText("titulo");

        dataField.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        dataField.setText("data");

        typeField.setFont(new java.awt.Font("FreeSans", 0, 24)); // NOI18N
        typeField.setText("tipo");

        statusField.setBackground(new java.awt.Color(51, 255, 51));
        statusField.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N
        statusField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusField.setText("Concluído");
        statusField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        statusField.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeField)
                .addGap(47, 47, 47)
                .addComponent(dataField)
                .addGap(26, 26, 26)
                .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataField)
                    .addComponent(typeField)
                    .addComponent(titleField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        MainFrame.getInstance().showAppointmentCad(appt, index);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataField;
    private javax.swing.JLabel statusField;
    private javax.swing.JLabel titleField;
    private javax.swing.JLabel typeField;
    // End of variables declaration//GEN-END:variables
}
